<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FirebaseAdmin" Version="3.*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\CskMasala.Shared.csproj" />
    <ProjectReference Include="..\CskMasala.Identity.Contracts\CskMasala.Identity.Contracts.csproj" />
    <ProjectReference Include="..\CskMasala.Identity.Domain\CskMasala.Identity.Domain.csproj" />
  </ItemGroup>
</Project>
