<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\CskMasala.Shared.csproj" />
    <ProjectReference Include="..\..\Identity\CskMasala.Identity.Contracts\CskMasala.Identity.Contracts.csproj" />
    <ProjectReference Include="..\CskMasala.Retail.Contracts\CskMasala.Retail.Contracts.csproj" />
    <ProjectReference Include="..\CskMasala.Retail.Domain\CskMasala.Retail.Domain.csproj" />
  </ItemGroup>
</Project>
